apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-player
  name: media-player-svc
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: media-player
  type: LoadBalancer
  loadBalancerIP: 34.95.107.218
  sessionAffinity: ClientIP