apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media-player
  name: media-player-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-player
  strategy: {}
  template:
    metadata:
      labels:
        app: media-player
    spec:
      volumes:
        - name: gcp-creds
          secret:
            secretName: gcp-creds
      containers:
      - image: jitendra5126/media-player:latest
        name: mediaplayer
        volumeMounts:
          - name: gcp-creds
            mountPath: /app/gcp-creds
        imagePullPolicy: Always
        ports:
          - containerPort: 6000
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /app/gcp-creds/keys.json
          - name: BUCKET
            value: media-9162
          - name: MONGO_URL
            value: mongodb://mongo:27017
        resources: {}
status: {}
