apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: jitendra5126/mongodb:v1
        name: mongo
        imagePullPolicy: Always
        ports:
          - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: volume-mount
      volumes:
        - name: volume-mount
          emptyDir: {}
status: {}
