apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uploader
  name: uploader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  strategy: {}
  template:
    metadata:
      labels:
        app: uploader
    spec:
      volumes:
        - name: gcp-creds
          secret:
            secretName: gcp-creds
      containers:
      - image: jitendra5126/uploader:latest
        name: uploader
        volumeMounts:
          - name: gcp-creds
            mountPath: /app/gcp-creds
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /app/gcp-creds/keys.json
          - name: BUCKET
            value: media-9162
        resources: {}
status: {}
