apiVersion: v1
kind: Service
metadata:
  labels:
    app: uploader
  name: uploader
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: uploader
  type: LoadBalancer
  loadBalancerIP: 34.95.107.218
  sessionAffinity: ClientIP